# Generated by Django 5.2.7 on 2025-10-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField()),
                ('url', models.URLField()),
                ('domain', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
